### PR TITLE
Fix reported package version

### LINKED ISSUE #49: Version reported as 0.0.0
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Not sure when this was introduced, but when installing the conda package, the pg8000 version is reported as 0.0.0. pip is fine.

```python
>>> import pg8000
>>> pg8000.__version__
'0.0.0'
>>> from importlib.metadata import version
>>> version("pg8000")
'0.0.0'
```

I noticed there was something related to the package version fixed earlier this year in pip, so maybe this is related?

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.5                h166bdaf_0    conda-forge
pg8000                    1.29.1             pyhd8ed1ab_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
python                    3.9.13          h2660328_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
scramp                    1.4.1              pyhd8ed1ab_0    conda-forge
setuptools                63.2.0           py39hf3d152e_0    conda-forge
sqlite                    3.39.1               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
```

### Environment info

```shell
active environment : pg8000-test
    active env location : /home/rschmidtke/miniconda3/envs/pg8000-test
            shell level : 1
       user config file : /home/rschmidtke/.condarc
 populated config files : /home/rschmidtke/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.8.13.final.0
       virtual packages : __linux=5.10.102.1=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rschmidtke/miniconda3  (writable)
      conda av data dir : /home/rschmidtke/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rschmidtke/miniconda3/pkgs
                          /home/rschmidtke/.conda/pkgs
       envs directories : /home/rschmidtke/miniconda3/envs
                          /home/rschmidtke/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.8.13 Linux/5.10.102.1-microsoft-standard-WSL2 ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #49

Upstream uses versioningit to determine the package version when building and falls back to 0.0.0 if nothing is found. The build process on conda-forge didn't incorporate that so it failed to properly report the version.

Ref: https://github.com/tlocke/pg8000/blob/b86633b4e67e3c2fd1f22c845008176c69b87e78/pyproject.toml#L12
Logs where correct versions is reported: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=572051&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=274

All of the issues upstream about this can be closed.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Note, the CircleCI failure is expected. There is something currently wrong with the conda-forge infrastructure. It is not actually being used. Only Azure needs to pass.

**Comment by BastianZim** [comment]
@maximerihouey If you have a sec, this fixes an issue with the way this package reports its version when built in conda-forge.

**Comment by maximerihouey** [comment]
@conda-forge-admin please rerender

**Comment by maximerihouey** [comment]
> @maximerihouey If you have a sec, this fixes an issue with the way this package reports its version when built in conda-forge.

Thank you very much @BastianZim .

**Review by maximerihouey — APPROVED** [review]

**Pull request merged**
